stages:
  - test
  - deploy

test_all:
  stage: test
  tags: [maven]
  except:
    - master
  script:
    - mvn clean install

test_unit:
  stage: test
  tags: [maven]
  only:
    - master
  script:
    - mvn clean install

deploy:
  stage: deploy
  only:
    - lab3
  script:
    - ls