image: maven:3.8.5-openjdk-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

test:
  stage: test
  allow_failure: true
  
  # Run the tests
  script:
    - echo "Executing SpringBoot scenarios with maven"
    - mvn clean test site
  
  # Store artifacts
  artifacts:
    when: always
    name: "SpringBoot Report"
    paths:
      - target/site/*
    expire_in: 24 h