version: '3.7'

services:
  auth-service-tests:
    build:
      context: auth-service
      dockerfile: Dockerfile-test
    depends_on:
      - db

  item-service-tests:
    build:
      context: item-service
      dockerfile: Dockerfile-test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/test
    depends_on:
      - db

  user-service-tests:
    build:
      context: user-service
      dockerfile: Dockerfile-test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/test
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGPORT: 5433